---
title: "Kaggle5/29"
author: "D"
date: "2017年5月29日"
output: html_document
---

###使用したライブラリ<br>
・caret (機械学習の使用)<br>
・dplyr (データの形成)<br>
・data.table  (大規模データの高速処理)<br>
・ggplot2 (描画ツール)<br>
・kernlab (SVMの使用)<br>
・makedummies (ダミー変数の作成)<br>
・ranger  （ランダムフォレストの使用）<br>
・stringr (文字列の処理)<br>

```{r include=FALSE}
library(caret)
library(dplyr)
library(data.table)
library(ggplot2)
library(kernlab)
library(makedummies)
library(ranger)
library(stringr)

```
###データの読み込み
```{r, }
df_train<-read.csv("train.csv", na.strings = (c("NA", "")))
df_test<-read.csv("test.csv", na.strings = (c("NA", "")))
```
これで, Pythonのデータとも一致する. 
###欠損値の処理
実際の欠損値（NA）の数を確認する.  
```{r}
na_count_train<-sapply(df_train, function(y) sum(is.na(y)))
na_count_test<-sapply(df_test, function(y) sum(is.na(y)))
na_count_train
na_count_test
```
名前の分割
```{r}
#separate Name
#(train)
name_sep_train<-str_split_fixed(df_train$Name, "[,.]", 3)
name_sep_train<-as.data.frame(name_sep_train)
colnames(name_sep_train)<-c("Surname","Honorific","Givenname")

df_train$Name<-name_sep_train$Honorific
#(test)
name_sep_test<-str_split_fixed(df_test$Name, "[,.]", 3)
name_sep_test<-as.data.frame(name_sep_test)
colnames(name_sep_test)<-c("Surname","Honorific","Givenname")

df_test$Name<-name_sep_test$Honorific
```  
次にdummy変数を導入する
```{r}
#make dummy variables
df_train_sub<-makedummies(df_train,basal_level=TRUE, as.is=c("Name", "Ticket", "Cabin"))
df_train_sub$Age<-as.integer(df_train_sub$Age)

df_test_sub<-makedummies(df_test,basal_level=TRUE, as.is=c("Name", "Ticket", "Cabin"))
df_test_sub$Age<-as.integer(df_test_sub$Age)
```
この結果からもわかるように, Cabinは欠損値が多いので取り除くこととする.

```{r}
#remove Cabin
df_train_mod<-df_train%>%
  dplyr::select(-PassengerId,-Ticket, -Cabin, -Name)

df_test_mod<-df_test%>%
  dplyr::select(-PassengerId,-Ticket, -Cabin, -Name)
```
また, 他の列に関しても欠損値を補完する.
今回は年齢は平均値で, 補完した.
```{r}
#remove Age`s NA
df_train_mod$Age<-ifelse(is.na(df_train_mod$Age), mean(df_train_mod$Age,na.rm=TRUE), df_train_mod$Age)
df_test_mod$Age<-ifelse(is.na(df_test_mod$Age), mean(df_test_mod$Age,na.rm=TRUE), df_test_mod$Age)
```

```{r}
#insert Embarked`s NA
df_train_mod$Embarked<-as.factor(df_train_mod$Embarked)
df_test_mod$Embarked<-as.factor(df_test_mod$Embarked)

df_train_mod$Embarked<-ifelse(is.na(df_train_mod$Embarked), 3, df_train_mod$Embarked)
df_test_mod$Embarked<-ifelse(is.na(df_test_mod$Embarked), 3, df_test_mod$Embarked)
```

```{r}
#test of  Fare`s NA
df_test_mod$Fare<-ifelse(is.na(df_test_mod$Fare), mean(df_test_mod$Fare,na.rm=TRUE), df_test_mod$Fare)
```


```{r}
fit<-ksvm(
  as.factor(Survived)~.,
  data = df_train_mod
)
pred <- predict(fit, df_test_mod)
```